### PR TITLE
Replace date-fns with dayjs to reduce bundle size

### PR DESCRIPTION
**Pull request by jahirfiquitiva**
This PR replaces `date-fns` [(~17.2 kB)](https://bundlephobia.com/package/date-fns) with `dayjs` [(~3 kB)](https://bundlephobia.com/package/dayjs), while keeping the same functionality and date format.

## Before

<details>
<summary><strong>vite-app</strong></summary>

```bash
vite-app:build: dist/index.html                   0.46 kB │ gzip:  0.30 kB
vite-app:build: dist/assets/index-154eb8fc.css   15.31 kB │ gzip:  3.29 kB
vite-app:build: dist/assets/index-91d57498.js   261.96 kB │ gzip: 83.23 kB
```

</details>

<details>
<summary><strong>create-react-app</strong></summary>

```bash
create-react-app:build: File sizes after gzip:
create-react-app:build: 
create-react-app:build:   68.2 kB (+3.77 kB)  build/static/js/main.8f7cde5d.js
create-react-app:build:   3.6 kB              build/static/css/main.732631ea.css
```

</details>

<details>
<summary><strong>custom-tweet-dub</strong></summary>

```bash
custom-tweet-dub:build: Route (app)                              Size     First Load JS
custom-tweet-dub:build: ┌ ○ /_not-found                          869 B          82.8 kB
custom-tweet-dub:build: ├ λ /light/[tweet]                       142 B           105 kB
custom-tweet-dub:build: └ ○ /light/mdx                           142 B           105 kB
custom-tweet-dub:build: + First Load JS shared by all            81.9 kB
custom-tweet-dub:build:   ├ chunks/0d9284fb-226a6bff1f0a31d6.js  53.3 kB
custom-tweet-dub:build:   ├ chunks/275-74368ff2a8347781.js       26.7 kB
custom-tweet-dub:build:   ├ chunks/main-app-b0a70ce855865355.js  219 B
custom-tweet-dub:build:   └ chunks/webpack-e329e726fc3d270d.js   1.74 kB
```

</details>

<details>
<summary><strong>next-app</strong></summary>

```bash
next-app:build: Route (app)                                Size     First Load JS
next-app:build: ┌ ○ /_not-found                            869 B          82.9 kB
next-app:build: ├ λ /api/tweet/[id]                        0 B                0 B
next-app:build: ├ λ /light/[tweet]                         5.27 kB         103 kB
next-app:build: ├ λ /light/cache/[tweet]                   285 B            98 kB
next-app:build: ├ ○ /light/mdx                             4.5 kB          102 kB
next-app:build: ├ λ /light/suspense/[tweet]                285 B            98 kB
next-app:build: └ λ /light/vercel-kv/[tweet]               285 B            98 kB
next-app:build: + First Load JS shared by all              82 kB
next-app:build:   ├ chunks/0d9284fb-ae7416485c018808.js    53.3 kB
next-app:build:   ├ chunks/275-8345a966cc84c9c7.js         26.7 kB
next-app:build:   ├ chunks/main-app-b0a70ce855865355.js    219 B
next-app:build:   └ chunks/webpack-e8fd018a1be7e4a4.js     1.82 kB
next-app:build: 
next-app:build: Route (pages)                              Size     First Load JS
next-app:build: ┌   /_app                                  0 B              79 kB
next-app:build: ├ ● /dark/[tweet]                          370 B          98.4 kB
next-app:build: ├   └ css/ced5d7019021380c.css             3.4 kB
next-app:build: └ ○ /dark/swr/[tweet]                      665 B          98.7 kB
next-app:build:     └ css/16ccfc9048631897.css             3.44 kB
next-app:build: + First Load JS shared by all              79.3 kB
next-app:build:   ├ chunks/framework-928b21e391283e8e.js   45.2 kB
next-app:build:   ├ chunks/main-5bb35c8745301dd4.js        31.7 kB
next-app:build:   ├ chunks/pages/_app-950debd3bbe9d167.js  297 B
next-app:build:   ├ chunks/webpack-e8fd018a1be7e4a4.js     1.82 kB
next-app:build:   └ css/34eb5f2b26f01226.css               263 B
```

</details>

## After

<details>
<summary><strong>vite-app (~6.55% smaller)</strong></summary>

```bash
vite-app:build: dist/index.html                   0.46 kB │ gzip:  0.30 kB
vite-app:build: dist/assets/index-154eb8fc.css   15.31 kB │ gzip:  3.29 kB
vite-app:build: dist/assets/index-c797ae0b.js   237.20 kB │ gzip: 77.95 kB
```

</details>

<details>
<summary><strong>create-react-app (~5.685% smaller)</strong></summary>

```bash
create-react-app:build: File sizes after gzip:
create-react-app:build: 
create-react-app:build:   64.43 kB (+4 B)  build/static/js/main.d9953dfe.js
create-react-app:build:   3.6 kB           build/static/css/main.732631ea.css
```

</details>

<details>
<summary><strong>custom-tweet-dub (~3.88% smaller)</strong></summary>

```bash
custom-tweet-dub:build: Route (app)                              Size     First Load JS
custom-tweet-dub:build: ┌ ○ /_not-found                          869 B          82.8 kB
custom-tweet-dub:build: ├ λ /light/[tweet]                       141 B           101 kB
custom-tweet-dub:build: └ ○ /light/mdx                           141 B           101 kB
custom-tweet-dub:build: + First Load JS shared by all            81.9 kB
custom-tweet-dub:build:   ├ chunks/0d9284fb-226a6bff1f0a31d6.js  53.3 kB
custom-tweet-dub:build:   ├ chunks/275-74368ff2a8347781.js       26.7 kB
custom-tweet-dub:build:   ├ chunks/main-app-b0a70ce855865355.js  219 B
custom-tweet-dub:build:   └ chunks/webpack-b498338c172250de.js   1.75 kB
```

</details>

<details>

<summary><strong>next-app (~3.97% smaller)</strong></summary>

```bash
next-app:build: Route (app)                                Size     First Load JS
next-app:build: ┌ ○ /_not-found                            869 B          82.9 kB
next-app:build: ├ λ /api/tweet/[id]                        0 B                0 B
next-app:build: ├ λ /light/[tweet]                         5.27 kB        99.1 kB
next-app:build: ├ λ /light/cache/[tweet]                   282 B          94.1 kB
next-app:build: ├ ○ /light/mdx                             4.5 kB         98.3 kB
next-app:build: ├ λ /light/suspense/[tweet]                282 B          94.1 kB
next-app:build: └ λ /light/vercel-kv/[tweet]               282 B          94.1 kB
next-app:build: + First Load JS shared by all              82 kB
next-app:build:   ├ chunks/0d9284fb-ae7416485c018808.js    53.3 kB
next-app:build:   ├ chunks/275-8345a966cc84c9c7.js         26.7 kB
next-app:build:   ├ chunks/main-app-b0a70ce855865355.js    219 B
next-app:build:   └ chunks/webpack-30b7c1423c2f9019.js     1.83 kB
next-app:build: 
next-app:build: Route (pages)                              Size     First Load JS
next-app:build: ┌   /_app                                  0 B              79 kB
next-app:build: ├ ● /dark/[tweet]                          370 B          94.5 kB
next-app:build: ├   └ css/ced5d7019021380c.css             3.4 kB
next-app:build: └ ○ /dark/swr/[tweet]                      666 B          94.8 kB
next-app:build:     └ css/16ccfc9048631897.css             3.44 kB
next-app:build: + First Load JS shared by all              79.3 kB
next-app:build:   ├ chunks/framework-928b21e391283e8e.js   45.2 kB
next-app:build:   ├ chunks/main-5bb35c8745301dd4.js        31.7 kB
next-app:build:   ├ chunks/pages/_app-950debd3bbe9d167.js  297 B
next-app:build:   ├ chunks/webpack-30b7c1423c2f9019.js     1.83 kB
next-app:build:   └ css/34eb5f2b26f01226.css               263 B
```

</details>

### CODE REVIEW

**Review by arturocr — CHANGES_REQUESTED** [review]
I saw [your post in LinkedIn](https://www.linkedin.com/in/jahirfiquitiva?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAACHaLx4BYUruyXRMXe9KzaTZ6oa39DY9uVc&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_content%3BOsEP4SdjQEK0cJtNUoXlOw%3D%3D), you mentioned that this specific formatting is not supported by `Intl.DateTimeFormat`, but that's not totally true, you can use it's `formatToParts` method and achieve the desired format.

Here's a function that will do it for you:

```typescript
const getFormattedDate = (date: Date) => {
  const options: Intl.DateTimeFormatOptions = {
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
    weekday: "short",
    month: "short",
    day: "numeric",
    year: "numeric",
  };
  const formatter = new Intl.DateTimeFormat("en-US", options);
  const parts = formatter.formatToParts(date);

  const partGetter = (partType: keyof Intl.DateTimeFormatPartTypesRegistry) =>
    parts.find((part) => part.type === partType)?.value;

  return `${partGetter("hour")}:${partGetter("minute")} ${partGetter(
    "dayPeriod"
  )} · ${partGetter("month")} ${partGetter("day")}, ${partGetter("year")}`;
};
```

This way you can ditch the use of a external library and make it even lighter.

There's a lot of room for improvement in this piece of code I just wrote.

[Here is](https://www.typescriptlang.org/play?#code/PTAEBEEMBcFNQGIHsBOBbGcWgK4GcBLAOwHNQBJI6AGwDoo4AVAtWZdGUAIwE9QABSCmg4USAMYoAUOKRE80UCVjR2GaHAAmDeAF5QACk0xYALggmAlKF0A+UAG8poULPmKkAB2gE5ec5Q09CbMrGowAPLevvI2js4uoAAWSKLmAEREOKwoBOLpADQJLmjEOHAZAEwAtJoEJATQhcXJqSgAjJXm0Cg4sEWJoADusLAA1sY8GXgpws2DaHLQSdOzTQOJkxlZOXnziTywQtvZsLn5GwC+ANwJbgqgAGao6lhxRLBDFFR0OqFsLxgBnSsCI1QAqgBlQqgLw+PyWW4ue6KTxCaB4OLPDgaM60bHqRhIAAK6LwRistzuflR6IA4io3voDGjhIweJ4zKAxrAeEhHt8gn8WACcaS2RzYHgAEqwBoKFA8ax2FqsjH44iaAws9HK+xq2jQSU2XT6NXszmWAD8tAAbpBqH0qS4UCpRERQAADAAkDjVDNxKGBKVE6Usl1Mvv9jLOwNKWTgYcuoCj9JjQZa6UmxLOvk06QS4dAAHaU3604G40skkmy9HK1nIDwkwU6xWsMDDkIk57bjcpDI-EhqLBaNQkCQDMpVIDcdoTAYPl8dAZLGupEA) a working example. Cheers! 🤓

**Comment by jahirfiquitiva** [comment]
@arturocr wow, I didn't know that was possible. Thanks for sharing!

Do you mind if I update my PR with your code as reference? (I would probably do a couple changes here and there) 

Thanks again! 😀

**Comment by arturocr** [comment]
> @arturocr wow, I didn't know that was possible. Thanks for sharing!
> 
> Do you mind if I update my PR with your code as reference? (I would probably do a couple changes here and there) 
> 
> Thanks again! 😀

Absolutely, go for it! 😁

**Comment by lfades** [comment]
Closing in favor of https://github.com/vercel/react-tweet/pull/163

**Pull request closed without merging**
